"""kr/pipeline/preflight_recovery.py — Item 2 (2026-04-30 RCA).

Auto-recovery hook called by ``preflight.run_and_record`` when
``check_universe_healthy`` fails with a *recoverable* reason_code.
Recovers OHLCV data from the authoritative PostgreSQL ``ohlcv`` table
via ``scripts/restore_ohlcv_from_db.py`` and triggers exactly one
re-check at the caller. Never loops.

Recoverable reason_codes (set by check_universe_healthy):
    dir_missing          — backtest/data_full/ohlcv/ does not exist
    csv_count_low        — fewer CSVs than MIN_CSV_COUNT
    history_sample_low   — sampled CSVs have insufficient history
    universe_size_low    — final universe build is too small

Non-recoverable (logic / env / config — kept as fail, no recovery attempt):
    import_failed   — universe_builder / pandas / Gen4Config import failed
    build_crash     — universe_builder raised
    config_import   — Gen4Config import failed
    config_init     — Gen4Config init failed
    pandas_missing  — pandas not available

Single-shot per (run_type, trade_date) — persisted via JSON marker so
restarts within the same trade_date do not re-trigger recovery
infinitely. The persisted marker also distinguishes auto vs manual
recovery for later forensics.

Public API:
    is_recoverable(check_result) -> bool
    try_auto_recover(run_type, check_name, check_result, state, *, logger=None)
        -> (recovered: bool, evidence: dict)
"""
from __future__ import annotations

import json
import logging
import sys
import time
from datetime import date, datetime
from pathlib import Path
from typing import Any, Optional

_log = logging.getLogger("gen4.pipeline.preflight_recovery")

# Reason codes that the OHLCV restore script can fix.
RECOVERABLE_REASON_CODES: frozenset[str] = frozenset({
    "dir_missing",
    "csv_count_low",
    "history_sample_low",
    "universe_size_low",
})

# Reason codes that are NOT data-related — recovery would not help.
NON_RECOVERABLE_REASON_CODES: frozenset[str] = frozenset({
    "import_failed",
    "build_crash",
    "config_import",
    "config_init",
    "pandas_missing",
})


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _marker_path(run_type: str, trade_date: str) -> Path:
    """Persisted single-shot marker (no in-memory state — restarts honored)."""
    return _repo_root() / "kr" / "data" / "pipeline" / (
        f"preflight_recovery_{trade_date}_{run_type}.json"
    )


def _load_marker(path: Path) -> Optional[dict]:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _save_marker(path: Path, payload: dict) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(payload, indent=2, default=str),
            encoding="utf-8",
        )
    except OSError as e:
        _log.warning(f"[PREFLIGHT_AUTO_RECOVERY_MARKER_WRITE_FAIL] {e!r}")


def _write_incident(
    *, run_type: str, check_name: str, reason_code: str,
    success: bool, evidence: dict,
) -> Optional[Path]:
    """Forensic incident MD. Distinct prefix from manual recovery."""
    try:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        incidents_dir = _repo_root() / "backup" / "reports" / "incidents"
        incidents_dir.mkdir(parents=True, exist_ok=True)
        verdict = "SUCCESS" if success else "FAIL"
        path = incidents_dir / (
            f"{ts}_preflight_auto_recovery_{verdict.lower()}.md"
        )
        lines = [
            f"# Preflight auto-recovery {verdict} — "
            f"{datetime.now().isoformat()}",
            "",
            "Auto-generated by `kr/pipeline/preflight_recovery.py` "
            "(Item 2). This is an **AUTOMATED** recovery attempt; "
            "see `_state_canary.md` and watchdog incidents for the "
            "triggering deletion event.",
            "",
            "## Trigger",
            "",
            f"- run_type:    `{run_type}`",
            f"- check_name:  `{check_name}`",
            f"- reason_code: `{reason_code}`",
            "",
            "## Evidence",
            "",
            "```json",
            json.dumps(evidence, indent=2, default=str),
            "```",
            "",
            "## Action",
            "",
            (
                "Recovery succeeded. Preflight will be re-run once. "
                "The pipeline orchestrator may also auto-unfreeze any "
                "previously ABANDONED step on its next tick (see "
                "Item 3)."
                if success else
                "Recovery FAILED. Preflight will return its original "
                "failure. Operator must run "
                "`scripts/restore_ohlcv_from_db.py --backup-existing "
                "--verify-universe` manually and inspect logs."
            ),
        ]
        path.write_text("\n".join(lines), encoding="utf-8")
        return path
    except Exception as e:  # noqa: BLE001
        _log.warning(f"[PREFLIGHT_AUTO_RECOVERY_INCIDENT_WRITE_FAIL] {e!r}")
        return None


def is_recoverable(check_result: Any) -> bool:
    """True iff `check_result.detail.reason_code` is in the recoverable set.

    Tolerates anything duck-typed: works on CheckResult or any object with
    ``.detail`` dict. Returns False on missing reason_code.
    """
    try:
        detail = getattr(check_result, "detail", None) or {}
        return detail.get("reason_code") in RECOVERABLE_REASON_CODES
    except Exception:  # noqa: BLE001
        return False


def _invoke_restore_script() -> tuple[int, str]:
    """Call ``scripts.restore_ohlcv_from_db.main`` in-process.

    Returns (exit_code, stderr-summary). Wraps the import inside the
    try block so any import error is captured as a soft failure, not
    a Python exception that would crash the pipeline tick.
    """
    try:
        # Bootstrap path so `scripts/` is importable. Also ensure shared/
        # is on path (the script does this internally too).
        repo_root = _repo_root()
        for p in (str(repo_root), str(repo_root / "kr")):
            if p not in sys.path:
                sys.path.insert(0, p)
        from scripts import restore_ohlcv_from_db as _ror  # noqa: WPS433
    except Exception as e:  # noqa: BLE001
        return -1, f"import failed: {e!r}"

    # Run with --backup-existing so any partial existing files are
    # archived before being overwritten. --verify-universe ensures
    # we don't return success on a still-broken state.
    try:
        rc = _ror.main(["--backup-existing", "--verify-universe"])
        return int(rc), ""
    except SystemExit as e:
        # argparse / main may sys.exit on error
        return int(e.code or 0), "SystemExit"
    except Exception as e:  # noqa: BLE001
        return -2, f"raised: {e!r}"


def try_auto_recover(
    *,
    run_type: str,
    check_name: str,
    check_result: Any,
    state: Any,
    logger: Optional[logging.Logger] = None,
) -> tuple[bool, dict]:
    """Attempt one-shot OHLCV recovery for a recoverable preflight failure.

    Returns (recovered, evidence). The caller is expected to re-run
    preflight ONCE if recovered=True; if recovered=False the original
    preflight failure stands.

    Idempotency:
      * Persists a marker file at
        ``kr/data/pipeline/preflight_recovery_{trade_date}_{run_type}.json``.
      * On second invocation for the same (trade_date, run_type) the
        marker is honored and recovery is NOT re-attempted, even
        across tray restarts.

    Never raises.
    """
    log = logger or _log

    # 1. Eligibility — only universe_healthy with a recoverable reason_code.
    if check_name != "universe_healthy":
        return False, {"recovered": False,
                       "reason": f"check_name={check_name} not recoverable"}
    if not is_recoverable(check_result):
        rc = getattr(check_result, "detail", {}) or {}
        return False, {
            "recovered": False,
            "reason": f"reason_code={rc.get('reason_code')!r} not in "
                      f"RECOVERABLE_REASON_CODES",
        }

    # 2. Idempotency marker — persisted across restarts.
    trade_date = getattr(state, "trade_date", None) or date.today().isoformat()
    marker_path = _marker_path(run_type, trade_date)
    prior = _load_marker(marker_path)
    if prior is not None:
        log.warning(
            f"[PREFLIGHT_AUTO_RECOVERY_SKIP] run_type={run_type} "
            f"trade_date={trade_date} prior_attempt_found "
            f"prior_success={prior.get('success')!r}"
        )
        return bool(prior.get("success")), {
            "recovered": bool(prior.get("success")),
            "reason": "prior_attempt_found",
            "prior": prior,
        }

    # 3. Run the restore script.
    reason_code = (getattr(check_result, "detail", {}) or {}).get(
        "reason_code", "?"
    )
    log.warning(
        f"[PREFLIGHT_AUTO_RECOVERY_BEGIN] run_type={run_type} "
        f"check={check_name} reason_code={reason_code} "
        f"trade_date={trade_date}"
    )
    t0 = time.time()
    exit_code, err_summary = _invoke_restore_script()
    elapsed = time.time() - t0
    success = (exit_code == 0)

    evidence = {
        "recovered": success,
        "exit_code": exit_code,
        "elapsed_sec": round(elapsed, 2),
        "reason_code": reason_code,
        "check_name": check_name,
        "run_type": run_type,
        "trade_date": trade_date,
        "started_at": datetime.now().isoformat(),
        "err_summary": err_summary,
    }

    # 4. Persist the attempt marker BEFORE re-check so a crash mid-recheck
    #    does not cause infinite re-attempts on next tick.
    _save_marker(marker_path, {"success": success, **evidence})

    # 5. Forensic incident
    incident = _write_incident(
        run_type=run_type, check_name=check_name,
        reason_code=reason_code, success=success, evidence=evidence,
    )
    if incident is not None:
        evidence["incident_path"] = str(incident)

    if success:
        log.warning(
            f"[PREFLIGHT_AUTO_RECOVERY_SUCCESS] run_type={run_type} "
            f"reason_code={reason_code} elapsed={elapsed:.1f}s "
            f"→ caller will re-check preflight ONCE"
        )
    else:
        log.critical(
            f"[PREFLIGHT_AUTO_RECOVERY_FAIL] run_type={run_type} "
            f"reason_code={reason_code} exit_code={exit_code} "
            f"err={err_summary} → original preflight failure stands"
        )

    return success, evidence


# ── Test helpers ─────────────────────────────────────────────────────


def reset_for_test(run_type: Optional[str] = None,
                    trade_date: Optional[str] = None) -> None:
    """Remove the persistent marker so tests can re-attempt recovery.

    With no args, removes ALL markers in the pipeline data dir.
    """
    pipeline_dir = _repo_root() / "kr" / "data" / "pipeline"
    if not pipeline_dir.exists():
        return
    if run_type and trade_date:
        targets = [_marker_path(run_type, trade_date)]
    else:
        targets = list(pipeline_dir.glob("preflight_recovery_*.json"))
    for p in targets:
        try:
            p.unlink()
        except OSError:
            pass
