"""kr/lifecycle/state_canary.py — Pre-startup state-integrity canary.

Detects the multi-file deletion pattern observed on 2026-04-30:

    * ``kr/state/portfolio_state_live.json``       — empty / missing
    * ``kr/state/runtime_state_live.json``         — empty / missing
    * ``backtest/data_full/ohlcv/`` directory      — missing entirely
    * ``backtest/data_full/index/KOSPI.csv``       — missing

The 04-30 incident was an *external* deletion (no Q-TRON code path
deletes these files in normal operation). Root cause was not
identified, so re-occurrence likelihood is HIGH. This canary catches
the *next* event the moment the engine notices, captures forensic
evidence before the deletion is masked by the recovery flow, and
fires a Telegram CRITICAL via the existing notify path.

Design contract (Jeff 2026-04-30):
    * **Read-only**. Never modifies state, never blocks startup.
    * **Best-effort**. Any internal exception is swallowed and
      logged at WARNING — the engine must continue regardless.
    * **Idempotent**. Calling twice in a single startup logs once
      via the `_already_fired_` cache; the snapshot file is unique
      per timestamp so duplicate writes are harmless either way.
    * **No live state injection**. The canary writes only to
      ``backup/reports/incidents/`` and the Telegram channel.

Usage:
    from lifecycle.state_canary import run_state_canary
    run_state_canary(config, logger)

Returns ``True`` if all checks pass, ``False`` otherwise. The caller
is expected to log the verdict but **not** to abort on False — the
RECON pipeline already handles cold-start resync; the canary's job
is observability, not control.
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger("gen4.state_canary")

# Single-fire cache so a startup that hits the canary twice doesn't
# spam Telegram. Reset on each new process start (module reload).
_already_fired: bool = False

# Thresholds
OHLCV_MIN_CSV_COUNT = 2500   # mirror preflight `MIN_CSV_COUNT`


# ── Individual checks ────────────────────────────────────────────────

def _check_state_file(path: Path) -> tuple[bool, str]:
    """Returns (ok, detail). False on missing / empty / unparseable JSON."""
    if not path.exists():
        return False, "missing"
    try:
        size = path.stat().st_size
    except OSError as e:
        return False, f"stat_error: {e}"
    if size == 0:
        return False, "empty (0 bytes)"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        return False, f"unreadable: {e}"
    if not isinstance(data, dict):
        return False, "not a JSON object"
    return True, f"ok size={size}B keys={len(data)}"


def _check_ohlcv_dir(ohlcv_dir: Path) -> tuple[bool, str]:
    """Existence + CSV count threshold."""
    if not ohlcv_dir.exists():
        return False, "directory missing"
    if not ohlcv_dir.is_dir():
        return False, "exists but not a directory"
    try:
        csvs = list(ohlcv_dir.glob("*.csv"))
    except OSError as e:
        return False, f"glob failed: {e}"
    n = len(csvs)
    if n < OHLCV_MIN_CSV_COUNT:
        return False, f"csv_count={n} < {OHLCV_MIN_CSV_COUNT}"
    return True, f"ok csv_count={n}"


def _check_kospi_csv(kospi_path: Path) -> tuple[bool, str]:
    if not kospi_path.exists():
        return False, "missing"
    try:
        size = kospi_path.stat().st_size
    except OSError as e:
        return False, f"stat_error: {e}"
    if size < 1024:  # <1KB is suspicious for a multi-year KOSPI series
        return False, f"truncated size={size}B"
    return True, f"ok size={size}B"


# ── Forensic snapshot ────────────────────────────────────────────────

def _write_forensic_snapshot(failures: list[tuple[str, str]],
                              base_dir: Path) -> Path | None:
    """Write a markdown report with the failure detail + filesystem
    listing of the parent directories so a future investigator can
    reconstruct what was around at the moment of the canary trigger.

    Returns the path written, or None on write failure.
    """
    try:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        incidents_dir = base_dir / "backup" / "reports" / "incidents"
        incidents_dir.mkdir(parents=True, exist_ok=True)
        path = incidents_dir / f"{ts}_state_canary.md"

        lines: list[str] = [
            f"# State Canary Trigger — {datetime.now().isoformat()}",
            "",
            "Auto-generated by `kr/lifecycle/state_canary.py`. The KR",
            "engine startup detected one or more critical files in an",
            "unexpected state. This snapshot captures the surrounding",
            "filesystem context so the deletion pattern can be analysed",
            "before the recovery / RECON flow rewrites the affected",
            "directories.",
            "",
            "## Failures",
            "",
        ]
        for name, detail in failures:
            lines.append(f"- **{name}**: {detail}")
        lines.append("")

        # Directory listings — limit to 30 entries so a healthy listing
        # doesn't drown out the signal but a wiped directory shows as
        # "(empty)".
        def _list_dir(label: str, dir_path: Path, limit: int = 30) -> None:
            lines.append(f"## `{label}` listing")
            lines.append("")
            if not dir_path.exists():
                lines.append("> *(directory missing)*")
                lines.append("")
                return
            try:
                entries = sorted(dir_path.iterdir(),
                                  key=lambda p: p.stat().st_mtime,
                                  reverse=True)
            except OSError as e:
                lines.append(f"> *(iter failed: {e})*")
                lines.append("")
                return
            if not entries:
                lines.append("> *(empty)*")
                lines.append("")
                return
            lines.append("```")
            for e in entries[:limit]:
                try:
                    st = e.stat()
                    mtime = datetime.fromtimestamp(st.st_mtime).isoformat(timespec="seconds")
                    kind = "DIR" if e.is_dir() else "FILE"
                    lines.append(f"{mtime}  {kind:4s}  {st.st_size:>10}  {e.name}")
                except OSError:
                    lines.append(f"???                {e.name}")
            if len(entries) > limit:
                lines.append(f"... ({len(entries) - limit} more)")
            lines.append("```")
            lines.append("")

        _list_dir("kr/state",                    base_dir / "kr" / "state")
        _list_dir("backtest/data_full",          base_dir / "backtest" / "data_full")
        _list_dir("backtest/data_full/ohlcv",    base_dir / "backtest" / "data_full" / "ohlcv", limit=10)
        _list_dir("backtest/data_full/index",    base_dir / "backtest" / "data_full" / "index")

        path.write_text("\n".join(lines), encoding="utf-8")
        return path
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[STATE_CANARY] forensic snapshot write failed: {e}")
        return None


def _send_telegram(failures: list[tuple[str, str]],
                    snapshot_path: Path | None) -> None:
    """Best-effort Telegram CRITICAL via the existing notify path."""
    try:
        from notify import telegram_bot as _tg
        bullets = "\n".join(f"• <b>{n}</b>: {d}" for n, d in failures)
        snap = (f"\nsnapshot: {snapshot_path.name}"
                if snapshot_path is not None else "")
        text = (
            f"<b>STATE_CANARY_TRIGGERED</b> 🚨\n"
            f"trade_date: {datetime.now().strftime('%Y-%m-%d')}\n"
            f"{bullets}{snap}\n"
            f"→ 즉시 운영자 점검 필요"
        )
        _tg.send(text, severity="CRITICAL")
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[STATE_CANARY] telegram send failed: {e}")


# ── Public API ───────────────────────────────────────────────────────

def run_state_canary(config: Any,
                      caller_logger: logging.Logger | None = None) -> bool:
    """Run all integrity checks. Returns True iff every check passed.

    Always-safe — internal exceptions are swallowed and reported as
    a single ``[STATE_CANARY] internal_error`` failure entry. Caller
    must not block on the return value.
    """
    global _already_fired
    log = caller_logger or logger

    failures: list[tuple[str, str]] = []
    try:
        base_dir = Path(getattr(config, "BASE_DIR", Path.cwd()))
        # KR is one level under repo root in the standard layout.
        repo_root = base_dir.parent if base_dir.name == "kr" else base_dir
        state_dir = base_dir / "state"
        ohlcv_dir = repo_root / "backtest" / "data_full" / "ohlcv"
        kospi_csv = repo_root / "backtest" / "data_full" / "index" / "KOSPI.csv"

        # Live mode — paper / shadow_test have their own files but the
        # 04-30 incident was on live. Add them later if ever observed.
        portfolio_path = state_dir / "portfolio_state_live.json"
        runtime_path = state_dir / "runtime_state_live.json"

        for label, ok, detail in [
            ("portfolio_state_live.json",
             *_check_state_file(portfolio_path)),
            ("runtime_state_live.json",
             *_check_state_file(runtime_path)),
            ("backtest/data_full/ohlcv",
             *_check_ohlcv_dir(ohlcv_dir)),
            ("backtest/data_full/index/KOSPI.csv",
             *_check_kospi_csv(kospi_csv)),
        ]:
            if ok:
                log.info(f"[STATE_CANARY_OK] {label}: {detail}")
            else:
                failures.append((label, detail))
                log.critical(f"[STATE_CANARY_FAIL] {label}: {detail}")
    except Exception as e:  # noqa: BLE001
        failures.append(("internal_error", repr(e)))
        log.warning(f"[STATE_CANARY] internal exception: {e}")

    if not failures:
        log.info("[STATE_CANARY_PASS] all checks ok")
        return True

    # Single-shot per process — re-running is wasted work and would
    # spam Telegram if the canary is hooked into multiple lifecycle
    # phases.
    if _already_fired:
        log.warning(
            f"[STATE_CANARY_REFIRE_SUPPRESSED] {len(failures)} failures "
            "(already fired earlier this process)"
        )
        return False

    _already_fired = True
    snapshot_path = _write_forensic_snapshot(
        failures, repo_root if 'repo_root' in dir() else Path.cwd()
    )
    _send_telegram(failures, snapshot_path)
    return False


def reset_for_test() -> None:
    """Test helper — clears the single-shot latch."""
    global _already_fired
    _already_fired = False
