"""
rebalancer.py — Monthly rebalance logic
=========================================
Compares current portfolio vs target, generates sell/buy order lists.

Key rules:
  - Sells first (free up cash), then buys
  - Equal weight: equity / n_selected
  - Trail-hit slots stay EMPTY until next rebalance (no mid-month fill)
  - Entry at next-day open (backtest) / market order (live)
"""
from __future__ import annotations
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("gen4.rebalancer")


@dataclass
class RebalOrder:
    """Order generated by rebalancer."""
    ticker: str
    side: str           # "BUY" or "SELL"
    quantity: int = 0
    target_amount: float = 0.0   # target allocation (for BUY sizing)
    reason: str = ""             # "REBALANCE_EXIT" or "REBALANCE_ENTRY"


def is_rebalance_day(trading_days_since_last: int, rebal_days: int = 21) -> bool:
    """
    Check if it's time to rebalance.

    Args:
        trading_days_since_last: Number of trading days since last rebalance.
        rebal_days: Rebalance frequency (21 = monthly).

    Returns:
        True if rebalance should occur.
    """
    return trading_days_since_last >= rebal_days


def compute_equal_weight(equity: float, n_stocks: int) -> float:
    """
    Target allocation per stock (equal weight).

    Args:
        equity: Total portfolio equity.
        n_stocks: Number of target stocks.

    Returns:
        Target amount per stock.
    """
    if n_stocks <= 0:
        return 0.0
    return equity / n_stocks


def compute_orders(current_positions: Dict[str, dict],
                   target_tickers: List[str],
                   total_equity: float,
                   current_cash: float,
                   buy_cost: float,
                   prices: Optional[Dict[str, float]] = None) -> Tuple[List[RebalOrder], List[RebalOrder]]:
    """
    Generate sell and buy orders for rebalance.

    Args:
        current_positions: {ticker: {qty, avg_price, ...}}
        target_tickers: New target portfolio tickers.
        total_equity: Current total equity (cash + holdings).
        current_cash: Current cash.
        buy_cost: Buy transaction cost for qty calculation.
        prices: {ticker: current_price} for qty calculation.

    Returns:
        (sell_orders, buy_orders)
        - Sells: stocks to remove (not in target)
        - Buys: new stocks to add (in target, not held)
    """
    current_set = set(current_positions.keys())
    target_set = set(target_tickers)
    prices = prices or {}

    # ── Sells: held but not in new target ──────────────────────────
    to_sell = current_set - target_set
    sell_orders = []
    for ticker in sorted(to_sell):
        pos = current_positions[ticker]
        qty = pos.get("quantity", pos.get("qty", 0))
        sell_orders.append(RebalOrder(
            ticker=ticker,
            side="SELL",
            quantity=qty,
            reason="REBALANCE_EXIT",
        ))

    # ── Buys: in target but not held ──────────────────────────────
    to_buy = target_set - current_set
    target_alloc = compute_equal_weight(total_equity, len(target_tickers))

    buy_orders = []
    # Estimate cash after sells (approximate)
    estimated_cash = current_cash
    for so in sell_orders:
        price = prices.get(so.ticker, 0)
        if price > 0:
            estimated_cash += so.quantity * price * (1 - buy_cost)  # approximate

    for ticker in target_tickers:  # preserve ranking order
        if ticker not in to_buy:
            continue
        price = prices.get(ticker, 0)
        if price <= 0:
            logger.warning(f"No price for {ticker}, skip buy")
            continue

        alloc = min(target_alloc, estimated_cash * 0.95)
        qty = int(alloc / (price * (1 + buy_cost)))
        if qty <= 0:
            continue

        cost = qty * price * (1 + buy_cost)
        if cost > estimated_cash:
            # Try smaller qty
            qty = int(estimated_cash * 0.95 / (price * (1 + buy_cost)))
            if qty <= 0:
                continue
            cost = qty * price * (1 + buy_cost)

        estimated_cash -= cost
        buy_orders.append(RebalOrder(
            ticker=ticker,
            side="BUY",
            quantity=qty,
            target_amount=alloc,
            reason="REBALANCE_ENTRY",
        ))

    logger.info(f"Rebalance: {len(sell_orders)} sells, {len(buy_orders)} buys "
                f"(target {len(target_tickers)}, held {len(current_positions)}, "
                f"keep {len(current_set & target_set)})")

    return sell_orders, buy_orders
